FROM mcr.microsoft.com/powershell:lts-ubuntu-22.04 as base

ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update \
    && apt-get install --no-install-recommends \
    apt-transport-https \
    apt-utils \
    ca-certificates \
    curl \
    git \
    iputils-ping \
    jq \
    lsb-release \
    # for terraform
    software-properties-common \
    unzip \
    wget

From base AS agent

# Prepare Terraform
RUN wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list

RUN apt-get update && apt-get install --no-install-recommends \
   dotnet-sdk-6.0 \
   # https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#supported-distributions
   # dotnet-sdk-8.0 \ #not available as of 12/6/23
   podman \
   python3-pip \
   terraform

RUN pip3 install podman-compose

#RUN terraform -version
#RUN podman --version

# Install Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Fetch the latest Bicep CLI binary
RUN curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64 \
   && chmod +x ./bicep \
   && mv ./bicep /usr/local/bin/bicep

ENV TARGETARCH=linux-x64

WORKDIR /azp

COPY ./start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]
#CMD ["/bin/bash"]
